import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd
from src.data_work.data_loader import load_anime_data, load_rating_data
from src.models.baseline import split_train_test, compute_bayesian_scores, recommend_popular_anime
from src.models.evaluator import evaluate, log_run

# --- load data (split already generated by split_data.py) ---
anime_df = load_anime_data("data/anime_clean.csv")
train    = pd.read_csv("data/train.csv")
test     = pd.read_csv("data/test.csv")
print(f"Train: {len(train)} rows | Test: {len(test)} rows")

# --- compute scores ---
print("Computing Bayesian scores from training data...")
scores = compute_bayesian_scores(train)
scores_named = scores.merge(anime_df[["anime_id", "name", "genre"]], on="anime_id", how="left")
scores_named = scores_named.sort_values("bayesian_score", ascending=False).reset_index(drop=True)
scores_named.to_csv("data/baseline_scores.csv", index=False)

# --- shared eval sample (same 1000 users across all models) ---
sample_users = pd.read_csv("data/eval_users.csv")["user_id"].tolist()
test_sample  = test[test["user_id"].isin(sample_users)]

print(f"Evaluating on {len(sample_users)} shared users (n=10, leave-one-out)...")
metrics = evaluate(
    lambda user_id, n: recommend_popular_anime(scores, train, user_id=user_id, n=n),
    test_sample, train, n=10
)
print(f"  Hit Rate : {metrics['hit_rate']}")
print(f"  Precision: {metrics['precision']}")
print(f"  Recall   : {metrics['recall']}")

print("\nTop 10 by Bayesian score:")
print(scores_named[["name", "rating_count", "avg_rating", "bayesian_score"]].head(10).to_string(index=False))

# --- record run in tracker ---
# Edit COMMENT before each run to describe what changed.
COMMENT = "Bayesian popularity baseline. m=80th pct. Recommends same top-10 to all users, no personalisation."
log_run(
    "report/model_performance_tracker.xlsx",
    "Baseline (Popularity)",
    metrics,
    {"split": "leave-one-out", "min_ratings": 5, "n_recommendations": 10},
    COMMENT,
)
print("✅ Results written to report/model_performance_tracker.xlsx")
